[tools]
bun = "latest"
zig = "latest"

[settings]

[settings.npm]
package_manager = "bun"

[tasks.start]
run = "cd packages/editor && bun src/index.tsx"

[tasks.dev]
run = "cd packages/editor && bun --hot src/index.tsx"

[tasks.build]
run = "bun run build.ts --target current"

[tasks."build:all"]
run = "bun run build.ts --target all"

[tasks."build:linux"]
run = "bun run build.ts --target linux-x64"

[tasks."build:linux-baseline"]
run = "bun run build.ts --target linux-x64-baseline"

[tasks."build:darwin"]
run = "bun run build.ts --target darwin-x64"

[tasks."build:darwin-baseline"]
run = "bun run build.ts --target darwin-x64-baseline"

[tasks."build:windows"]
run = "bun run build.ts --target windows-x64"

[tasks."build:windows-baseline"]
run = "bun run build.ts --target windows-x64-baseline"
